#!/bin/bash
# shellcheck source=scripts/functions.sh
source "/home/steam/server/functions.sh"

config_file="/7d2d/serverconfig.xml"
config_dir=$(dirname "$config_file")

mkdir -p "$config_dir" || exit

export SERVER_NAME=${SERVER_NAME:-"My Game Host"}
export SERVER_DESCRIPTION=${SERVER_DESCRIPTION:-"A 7 Days to Die server"}
export SERVER_WEBSITE_URL=${SERVER_WEBSITE_URL:-""}
export SERVER_PASSWORD=${SERVER_PASSWORD:-""}
export SERVER_LOGIN_CONFIRMATION_TEXT=${SERVER_LOGIN_CONFIRMATION_TEXT:-""}
export REGION=${REGION:-"NorthAmericaEast"}
export LANGUAGE=${LANGUAGE:-"English"}
export SERVER_PORT=${SERVER_PORT:-"26900"}
export SERVER_VISIBILITY=${SERVER_VISIBILITY:-"2"}
export SERVER_DISABLED_NETWORK_PROTOCOLS=${SERVER_DISABLED_NETWORK_PROTOCOLS:-"SteamNetworking"}
export SERVER_MAX_WORLD_TRANSFER_SPEED_KIBS=${SERVER_MAX_WORLD_TRANSFER_SPEED_KIBS:-"512"}
export SERVER_MAX_PLAYER_COUNT=${SERVER_MAX_PLAYER_COUNT:-"8"}
export SERVER_RESERVED_SLOTS=${SERVER_RESERVED_SLOTS:-"0"}
export SERVER_RESERVED_SLOTS_PERMISSION=${SERVER_RESERVED_SLOTS_PERMISSION:-"100"}
export SERVER_ADMIN_SLOTS=${SERVER_ADMIN_SLOTS:-"0"}
export SERVER_ADMIN_SLOTS_PERMISSION=${SERVER_ADMIN_SLOTS_PERMISSION:-"0"}
export WEB_DASHBOARD_ENABLED=${WEB_DASHBOARD_ENABLED:-"true"}
export WEB_DASHBOARD_PORT=${WEB_DASHBOARD_PORT:-"8080"}
export WEB_DASHBOARD_URL=${WEB_DASHBOARD_URL:-""}
export ENABLE_MAP_RENDERING=${ENABLE_MAP_RENDERING:-"true"}
export TELNET_ENABLED=${TELNET_ENABLED:-"true"}
export TELNET_PORT=${TELNET_PORT:-"8081"}
export TELNET_PASSWORD=${TELNET_PASSWORD:-""}
export TELNET_FAILED_LOGIN_LIMIT=${TELNET_FAILED_LOGIN_LIMIT:-"10"}
export TELNET_FAILED_LOGINS_BLOCKTIME=${TELNET_FAILED_LOGINS_BLOCKTIME:-"10"}
export TERMINAL_WINDOW_ENABLED=${TERMINAL_WINDOW_ENABLED:-"true"}
export ADMIN_FILE_NAME=${ADMIN_FILE_NAME:-"serveradmin.xml"}
export SERVER_ALLOW_CROSSPLAY=${SERVER_ALLOW_CROSSPLAY:-"false"}
export EAC_ENABLED=${EAC_ENABLED:-"true"}
export IGNORE_EOS_SANCTIONS=${IGNORE_EOS_SANCTIONS:-"false"}
export HIDE_COMMAND_EXECUTION_LOG=${HIDE_COMMAND_EXECUTION_LOG:-"0"}
export MAX_UNCOVERED_MAP_CHUNKS_PER_PLAYER=${MAX_UNCOVERED_MAP_CHUNKS_PER_PLAYER:-"131072"}
export PERSISTENT_PLAYER_PROFILES=${PERSISTENT_PLAYER_PROFILES:-"false"}
export MAX_CHUNK_AGE=${MAX_CHUNK_AGE:-"-1"}
export SAVE_DATA_LIMIT=${SAVE_DATA_LIMIT:-"-1"}
export GAME_WORLD=${GAME_WORLD:-"Navezgane"}
export WORLD_GEN_SEED=${WORLD_GEN_SEED:-"MyGame"}
export WORLD_GEN_SIZE=${WORLD_GEN_SIZE:-"6144"}
export GAME_NAME=${GAME_NAME:-"MyGame"}
export GAME_MODE=${GAME_MODE:-"GameModeSurvival"}
export GAME_DIFFICULTY=${GAME_DIFFICULTY:-"1"}
export BLOCK_DAMAGE_PLAYER=${BLOCK_DAMAGE_PLAYER:-"100"}
export BLOCK_DAMAGE_AI=${BLOCK_DAMAGE_AI:-"100"}
export BLOCK_DAMAGE_AI_BM=${BLOCK_DAMAGE_AI_BM:-"100"}
export XP_MULTIPLIER=${XP_MULTIPLIER:-"100"}
export PLAYER_SAFE_ZONE_LEVEL=${PLAYER_SAFE_ZONE_LEVEL:-"5"}
export PLAYER_SAFE_ZONE_HOURS=${PLAYER_SAFE_ZONE_HOURS:-"5"}
export BUILD_CREATE=${BUILD_CREATE:-"false"}
export DAY_NIGHT_LENGTH=${DAY_NIGHT_LENGTH:-"60"}
export DAY_LIGHT_LENGTH=${DAY_LIGHT_LENGTH:-"18"}
export BIOME_PROGRESSION=${BIOME_PROGRESSION:-"true"}
export STORM_FREQ=${STORM_FREQ:-"100"}
export DEATH_PENALTY=${DEATH_PENALTY:-"1"}
export DROP_ON_DEATH=${DROP_ON_DEATH:-"1"}
export DROP_ON_QUIT=${DROP_ON_QUIT:-"0"}
export BEDROLL_DEAD_ZONE_SIZE=${BEDROLL_DEAD_ZONE_SIZE:-"15"}
export BEDROLL_EXPIRY_TIME=${BEDROLL_EXPIRY_TIME:-"45"}
export ALLOW_SPAWN_NEAR_FRIEND=${ALLOW_SPAWN_NEAR_FRIEND:-"2"}
export MAX_SPAWNED_ZOMBIES=${MAX_SPAWNED_ZOMBIES:-"64"}
export MAX_SPAWNED_ANIMALS=${MAX_SPAWNED_ANIMALS:-"50"}
export SERVER_MAX_ALLOWED_VIEW_DISTANCE=${SERVER_MAX_ALLOWED_VIEW_DISTANCE:-"12"}
export MAX_QUEUED_MESH_LAYERS=${MAX_QUEUED_MESH_LAYERS:-"1000"}
export ENEMY_SPAWN_MODE=${ENEMY_SPAWN_MODE:-"true"}
export ENEMY_DIFFICULTY=${ENEMY_DIFFICULTY:-"0"}
export ZOMBIE_FERAL_SENSE=${ZOMBIE_FERAL_SENSE:-"0"}
export ZOMBIE_MOVE=${ZOMBIE_MOVE:-"0"}
export ZOMBIE_MOVE_NIGHT=${ZOMBIE_MOVE_NIGHT:-"3"}
export ZOMBIE_FERAL_MOVE=${ZOMBIE_FERAL_MOVE:-"3"}
export ZOMBIE_BM_MOVE=${ZOMBIE_BM_MOVE:-"3"}
export BLOOD_MOON_FREQUENCY=${BLOOD_MOON_FREQUENCY:-"7"}
export BLOOD_MOON_RANGE=${BLOOD_MOON_RANGE:-"0"}
export BLOOD_MOON_WARNING=${BLOOD_MOON_WARNING:-"8"}
export BLOOD_MOON_ENEMY_COUNT=${BLOOD_MOON_ENEMY_COUNT:-"8"}
export LOOT_ABUNDANCE=${LOOT_ABUNDANCE:-"100"}
export LOOT_RESPAWN_DAYS=${LOOT_RESPAWN_DAYS:-"7"}
export AIR_DROP_FREQUENCY=${AIR_DROP_FREQUENCY:-"72"}
export AIR_DROP_MARKER=${AIR_DROP_MARKER:-"true"}
export PARTY_SHARED_KILL_RANGE=${PARTY_SHARED_KILL_RANGE:-"100"}
export PLAYER_KILLING_MODE=${PLAYER_KILLING_MODE:-"3"}
export LAND_CLAIM_COUNT=${LAND_CLAIM_COUNT:-"5"}
export LAND_CLAIM_SIZE=${LAND_CLAIM_SIZE:-"41"}
export LAND_CLAIM_DEAD_ZONE=${LAND_CLAIM_DEAD_ZONE:-"30"}
export LAND_CLAIM_EXPIRY_TIME=${LAND_CLAIM_EXPIRY_TIME:-"7"}
export LAND_CLAIM_DECAY_MODE=${LAND_CLAIM_DECAY_MODE:-"0"}
export LAND_CLAIM_ONLINE_DURABILITY_MODIFIER=${LAND_CLAIM_ONLINE_DURABILITY_MODIFIER:-"4"}
export LAND_CLAIM_OFFLINE_DURABILITY_MODIFIER=${LAND_CLAIM_OFFLINE_DURABILITY_MODIFIER:-"4"}
export LAND_CLAIM_OFFLINE_DELAY=${LAND_CLAIM_OFFLINE_DELAY:-"0"}
export DYNAMIC_MESH_ENABLED=${DYNAMIC_MESH_ENABLED:-"true"}
export DYNAMIC_MESH_LAND_CLAIM_ONLY=${DYNAMIC_MESH_LAND_CLAIM_ONLY:-"true"}
export DYNAMIC_MESH_LAND_CLAIM_BUFFER=${DYNAMIC_MESH_LAND_CLAIM_BUFFER:-"3"}
export DYNAMIC_MESH_MAX_ITEM_CACHE=${DYNAMIC_MESH_MAX_ITEM_CACHE:-"3"}
export TWITCH_SERVER_PERMISSION=${TWITCH_SERVER_PERMISSION:-"90"}
export TWITCH_BLOOD_MOON_ALLOWED=${TWITCH_BLOOD_MOON_ALLOWED:-"false"}
export QUEST_PROGRESSION_DAILY_LIMIT=${QUEST_PROGRESSION_DAILY_LIMIT:-"4"}

cat > "$config_file" <<EOF
$(envsubst < /home/steam/server/templates/serverconfig.xml.template)
EOF
